### ISSUE TITLE
Tests for MiniMeToken

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-core#120]
Check Coverall for uncovered lines.

**Comment by cpurta** [comment]
Would like to take this one on. What exactly is the goal here?

**Comment by izqui** [comment]
Add tests for covering both basic ERC20 functionality and MiniMe specific functionality such as cloning.

For the ANT sale contract some tests were done https://github.com/aragon/aragon-network-token/blob/master/test/TestMiniMeCloning.sol, and there are also some tests in the MiniMe token repo that could be reused

**Comment by cpurta** [comment]
Correct me if I am mistaken but it seems like the ERC20 functionality is covered in `test/zeppelin_StandardToken.js`
