### ISSUE TITLE
Add "how to" guides

### ISSUE THREAD

**Issue by mohsenghajar** [aragon/aragon-core#128]
The first thing I encountered:
How to add a new entity?  It seems in order to transfer shares to another employee, he/she should be first an entity and accessible through the drop-down list.  Not clear how to add new entity.

**Comment by izqui** [comment]
You can transfer shares by just entering the address of the entity you want to send them to.

Closing this issue as issues in this repo are related to the aragon-core smart contracts only, https://github.com/aragon/aragon is a better place to ask.

**Comment by luisivan** [comment]
Just wanted to say that we will work on tutorials soon @mohsenghajar
