### ISSUE TITLE
Move core apps and interfaces to their own repositories

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-core#136]
In order to facilitate a better developer experience for 3rd party developers, we should move the core abstractions (e.g. the Kernel interface, AppProxy etc. contracts) into its own repository (or package, we can keep this as a monorepo if we want to).

At the same time, we could also move out the core apps into their own repository (or package).

**Proposal**

- One repository (or package) for the default kernel
- One repository (or package) for the interfaces
- One repository (or package) for each of the core apps

I think it would make sense to keep the kernel and interfaces in the same repository, but in different packages (e.g. through lerna), but to have one repository per core app and list those in the wiki, since the core apps will need a front-end, and having the contracts + frontend in the same repository plays nicely with `aragon-dev-cli`.

**Comment by onbjerg** [comment]
Thoughts? @izqui

**Comment by onbjerg** [comment]
Core apps will be moved to aragon/aragon-apps, interfaces will stay here.

Closable when apps are removed from this repository.

**Comment by izqui** [comment]
Closed by #140
