### ISSUE TITLE
DelegateProxy makes gas estimations break

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#141]
In the Byzantium implementation of DelegateProxy, in case the underlying `delegatecall` fails (result is 0), we are doing a revert regardless of how it failed. 

The problem is that when clients estimate how much any delegated call needs, the delegate proxy will fail with a revert as result of an out of gas in the call. This makes clients think the call was executed with enough gas, but it failed with a revert because of some issue with the call. As a result, the gas estimation for calls is very low, which makes it go out of gas.

A quick solution for this is to do `invalid()` instead of `revert(...)` when the result is 0, but we would be losing the advantage of apps reverting cheaply (and in the future being able to return error messages).

The ideal solution would be to analyze the gas decrease with the delegatecall, to try to compute whether it was an out of gas (if it spent all given gas). This is not so trivial given that we need to take into account the 63/64 gas rule for calls.

**Comment by karalabe** [comment]
Geth should consider a revert the same as OOG and should bump the gas limit. Do you have a repro code for me to try? Perhaps deployed on the Rinkeby testnet?

**Comment by izqui** [comment]
I'm not being able to reproduce right now, gas estimation seems to be working correctly now. I don't have the exact code I tested it with back in the day but it was similar to [this](https://gist.github.com/izqui/28070d4653d1b50da89fbd7e9024c863):

I have one of the transactions that went out of gas because of this issue: https://ropsten.etherscan.io/tx/0x4145c08f345e2fadabed481f9323b6dad69cb6d6ea2e758b7b06ea3214399a46.

**Comment by karalabe** [comment]
Geth 1.7.0 didn't correctly estimate REVERTs post Byzantium, but that only appeared on Ropsten and was fixed before mainnet Byzantium (v.1.7.1) switch-over https://github.com/ethereum/go-ethereum/pull/15030. Perhaps that's when you saw the error?

**Comment by izqui** [comment]
I think that is the case, yes. Thanks for letting me know :)

Closing the issue for now as it seems it has been resolved.
