### ISSUE TITLE
App initialization front-running

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#144]
When apps are deployed without using a Factory (after initial DAO setup), they require two steps for creation: first Proxy deploy, then initialization. This can result in an attacker introducing a transaction between both and initializing the app with different parameters (which may go unnoticed).

Possible solutions:
- Make https://github.com/aragon/aragon-core 's `Initializable` inherit from `Ownable` and then make `Initializable` a part of AppProxy default contract, so after a proxy is created it can only be initialized by the same account.

- Add a new optional parameter to AppProxy's initializer for data to be executed on the target contract on initialization. This approach requires the app code to be set before creating the app proxy. This would look like this:

```
    function AppProxy(IKernel _kernel, bytes32 _appId, bytes _initializeData) {
        kernel = _kernel;
        appId = _appId;
        if (_initializeData.length > 0)
             this.call(_initializeData);
    }
```

**Comment by onbjerg** [comment]
So, one thing for approach one:

Wouldn't there be an issue in making it ownable, given that proxies might actually be deployed by other apps (e.g. the voting app)?

Imagine someone deploying the proxy, and then initializing the app afterwards, but the permissions changed in the meantime, so the transaction path is no longer ending on the voting app - in which case the app is uninitializable.

**Comment by izqui** [comment]
That's a good point, i'm more convinced about approach 2
