### ISSUE TITLE
Linter: upgrade to v1

### ISSUE THREAD

**Issue by duaraghav8** [aragon/aragon-core#146]
Hi Guys,
Its been quite a while since [Solium](https://github.com/duaraghav8/Solium) `v1` was released. It comes with significant improvements including bug fixes, automatic code fixing & new security checks for contract code.

I'm raising this issue to simply make you aware, since v1 will significantly improve your workflow.

Adoption is pretty simple:

`npm i -g solium`

Going by your current `.soliumrc.json`, your new `.soliumrc.json` would look like:

```json
{
  "extends": "solium:all",
  "plugins": ["security"],
  "rules": {
    "mixedcase": "off"
  }
}
```
If, for eg, you'd like to disable a security rule you don't agree with, simply add `"security/rule-name": "off"` inside `rules` object.

Run normally using `solium -d contracts/` or `solium -d contracts/ --fix` to apply code fixes (wherever possible).
(Stating the obvious here) Recommend use `--fix` inside your clone so its easy for you to `git diff` and `git checkout` if necessary.

[Usage docs](http://solium.readthedocs.io/en/latest/user-guide.html)
[List of Security Rules](https://github.com/duaraghav8/solium-plugin-security#list-of-rules)

Please do not hesitate in closing this issue if you feel its not currently a priority. However, I do recommend that you upgrade to further improve contract security. Feel free to ask me anything!

**Comment by izqui** [comment]
Thanks for pointing it out! Will definitely be updating soon

**Comment by onbjerg** [comment]
Nice improvements, thanks for pinging 😊

**Comment by izqui** [comment]
Closed by #147

**Comment by izqui** [comment]
I actually overlooked the PR @cpurta and it doesn't update the solium dependency to 1.0.x, it just changes the rules but they are not being enforced yet.

**Comment by cpurta** [comment]
@duaraghav8 currently seeing errors in #150 CI tests due to inline assembly. Is there currently a way for solium to ignore inline assembly as a part of the rules in the `soliumrc.json`?

**Comment by duaraghav8** [comment]
@cpurta absolutely. Inside `.soliumrc.json`'s `rules` object, add:
`"security/no-inline-assembly": "warning"`

This ensures that the linter still notifies you of the issue but doesn't cause a CI fail since only an `error` (default value of no assembly rule) causes exit code > 0.

Alternatively, you could use `"security/no-inline-assembly": "off"` to turn it off altogether (not recommended)

For your future ref:
- [List of security/ rules](https://github.com/duaraghav8/solium-plugin-security/tree/661c2b4f1ea0aa1fea95a78abc3d2287d63f3048#list-of-rules)
- [List of Solium core rules](http://solium.readthedocs.io/en/latest/user-guide.html#list-of-core-rules)

Please let me know if you face any other issues
