### ISSUE TITLE
Implement dividend sharing using MiniMe cloning

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#15]
Dividends workflow: 
- Create dividend sharing contract and transfer to it all the tokens that is going to share.
- Contract will do a clone of the token at that block height.
- When a holder calls the contract `collect()` function, his tokens get burned and gets a proportional share of all assets being shared (be careful with the rounding! https://medium.com/@weka/dividend-bearing-tokens-on-ethereum-42d01c710657)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by onbjerg** [comment]
Still relevant? Using Commiteth!

**Comment by izqui** [comment]
We will add it later as an Aragon app
