### ISSUE TITLE
Delegatecall proxy does not reserve memory

### ISSUE THREAD

**Issue by chriseth** [aragon/aragon-core#176]
Just found this by chance, so the issue might be wrong because I did not look at any context, but it seems that the delegatecall proxy does not reserve / claim the memory it uses:

https://github.com/aragon/aragon-core/blob/f42f5a4bd62c6e9655a3a4e6c6f165300a63287d/contracts/common/DelegateProxy.sol#L18

There is something like `mstore(0x40, add(mload(0x40), size))` missing (at best even round size to next multiple of `0x20`).

**Comment by izqui** [comment]
Would this be a problem if we always immediately return/exit the context? 

https://github.com/aragon/aragon-core/blob/f42f5a4bd62c6e9655a3a4e6c6f165300a63287d/contracts/common/DelegateProxy.sol#L21-L22

**Comment by chriseth** [comment]
Hm of course you are right!

**Comment by izqui** [comment]
Thanks for the help (and all your work!) :)
