### ISSUE TITLE
Implement on-chain factories that setup a default company

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#20]
Blocked by almost every major issue for the v0.4 millestone.

With the new architecture building an organization is almost as doing a LEGO puzzle.

We should work on a factory that with 1-3 transactions sets up all the needed contracts for the organization with some sane defaults, as the current [CompanyFactory](https://github.com/aragon/aragon-core/blob/monolith/contracts/factories/CompanyFactory.sol) works in v0.3

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by DavidKnott** [comment]
@izqui I'd love to take a crack at this

**Comment by izqui** [comment]
Cool! I'm not sure how practical I'd be to start now given that so many applications are yet to be adapted to the new arch. 

Anyway what this would need to have is:

- [ ] Deploy all needed contracts.
- [ ] Deploy 1 token contract for organization and allocate 1 token to the creator (so it can start using it)
- [ ] Set bylaws to safe defaults

**Comment by DavidKnott** [comment]
@izqui Is there an issue that you see as more practical for me to work on?
