### ISSUE TITLE
Resolve truffle solidity test library linking for BylawsLib unit tests

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#22]
Unit tests for BylawsLib are failing because Solidity is failing to link the lib to the test.

https://travis-ci.org/aragon/aragon-core/builds/242547229?utm_source=github_status&utm_medium=notification

This locked #11 for a day, then decided to remove it from the PR.

**Comment by onbjerg** [comment]
Is it perhaps the naming of the test contract?

From the [documentation](http://truffleframework.com/docs/getting_started/solidity-tests#test-contract-names):

>All test contracts must start with Test, using an uppercase T. This distinguishes this contract apart from test helpers and project contracts (i.e., the contracts under test), letting the test runner know which contracts represent test suites.
