### ISSUE TITLE
Refactor how contract artifacts are generated, contracts deployed and imported into dapp

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#3]
Migrated from https://github.com/aragon/issues/issues/68

https://github.com/aragon/aragon-core/pull/1 removed the truffle build directory from the repo, which aragon-dapp uses for fetching the contract artifacts (and the deployed contract addresses).

@onbjerg proposal: https://gist.github.com/onbjerg/b828aa3bdcc6f9ad0a316a2bfc98a304

Looking into https://github.com/lerna/lerna too

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
