### ISSUE TITLE
Clarify usage of babel

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-core#33]
Is there any particular reasoning behind depending on babel? It doesn't seem to be used, and the ``index.js`` file is fully supported in the latest Node version.

**Comment by izqui** [comment]
It is used here https://github.com/aragon/aragon-core/blob/master/truffle.js#L2 so we can do async/await in truffle tests. I don't know whether this is needed anymore, this was copied from Zeppelin

**Comment by onbjerg** [comment]
I think Node 7.6 and after supports async/await natively. I can test this out later.

**Comment by onbjerg** [comment]
Alright, so ``await/async`` is supported, but the spread operator doesn't seem to be fully supported, which is also used in some places (e.g. ``{ a, ...b }``).

**Comment by onbjerg** [comment]
Usage was clarified, not possible to live without Babel for now -- unless we change the code, but it's a nitpick since we're only publishing the built contracts anyway.
