### ISSUE TITLE
Test multiple transaction types dispatching

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#4]
Unit tests are needed to cover:

Kernel:
- [ ] Vanilla ETH transactions (when ETH gets wrapped into the EtherToken)
- [ ] Presigned ETH transactions (test payloads are non-reusable)
- [ ] Token receivers (ERC223 and approveAndCall compatibility)

Dispatcher organ:
- [ ] Not dispatching when action is not allowed
- [ ] Not dispatching when no organ can perform the action
- [ ] Dispatching to an app and checking app is sandboxed

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
