### ISSUE TITLE
Test bylaws app integration

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#6]
[Bylaws app](https://github.com/aragon/aragon-core/blob/daaa2bad8281ca100b88b210100a869355d62ecf/apps/bylaws/BylawsApp.sol) is compiling and should be ready to work in the current system. 

Integration needs testing and unit tests to ensure the bylaws app does access control for the DAO.

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by izqui** [comment]
Resolved by #11
