### ISSUE TITLE
Implement incremental nonces for preauth transactions below a certain nonce

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#67]
Right now nonces are just used for checking a certain preauthorized payload be executed just once, while also allowing for executing different times the same preauth action (with different signatures, of course)

As proposed in this [EIP comment](https://github.com/ethereum/EIPs/issues/662#issuecomment-314630438), it could be interesting to treat nonces below a certain `x` threshold (`x = 10 ^ 10` seems good enough) as an incremental nonce. This means that a preauthorized transaction that has a nonce `n` below `x`, will only be executed iff last executed preauth tx for that address was `n - 1`.

It would require adding an additional storage key for keeping track of address nonces.

**Comment by Quazia** [comment]
I'd like to take a crack at this.

**Comment by izqui** [comment]
Awesome, all yours!

**Comment by izqui** [comment]
No longer relevant
