### ISSUE TITLE
Rethink DAOMessage logic

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#7]
With the changes introduced in #1 related to storage, DAOMessage can no longer be saved [the way it was](https://github.com/aragon/aragon-core/blob/daaa2bad8281ca100b88b210100a869355d62ecf/contracts/kernel/AbstractKernel.sol#L9). It could be saved as storage or other solutions could be thought.

The requirement is to maintain the DAO calling context as we move through different organs via delagatecalls and being able to pass this context to the applications.

Implications related to reentrancy and DAOMessage not being changed need to be properly thought.

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by izqui** [comment]
Closed by #10. 

Maintaining old system for now
