### ISSUE TITLE
Failure downloading nodejs dependencies

### ISSUE THREAD

**Issue by mxmauro** [aragon/aragon-core#75]
Hi,

The file `npm-shrinkwrap.jon` contains characters of a failed merge (`<<<`, `HEAD`, `>>>`) and `npm install` command fails to download dependencies.

Regards,
Mauro.

**Comment by onbjerg** [comment]
Hey @mxmauro,

Closing this issue since this is no longer the case 🙂

**Comment by mxmauro** [comment]
Hi @onbjerg, yes I know you are doing some refactoring/improvements :) Thanks.
