### ISSUE TITLE
Add ability to revoke token grants in ownership app 

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#77]
We need to add a way to revoke token grants that returns tokens to the DAO. 

Base implementation for a complex revoke: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/VestedToken.sol#L74

**Comment by eyezick** [comment]
this one still open?

**Comment by eyezick** [comment]
Cool, I'm on it

**Comment by izqui** [comment]
Implemented in Token Manager in aragon-apps
