### ISSUE TITLE
Generate factory dependency

### ISSUE THREAD

**Issue by DeveloppSoft** [aragon/aragon-core#79]
Just discovered that [scripts/generate_factory.js](https://github.com/aragon/aragon-core/blob/master/scripts/generate_factory.js) is using a dependency (`solidity-inspector`) with a relative path (see https://github.com/aragon/aragon-core/blob/master/scripts/generate_factory.js#L5) which makes it unusable.

After a quick search I wasn't able to find it online.

**Comment by izqui** [comment]
Good catch, made a PR to solve this. 

It is now published to npm and github: https://github.com/aragon/solidity-inspectior

**Comment by DeveloppSoft** [comment]
Thanks, closing in favor of #80
