### ISSUE TITLE
Develop bot that automatically funds Commiteth bounties

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#8]
Right now all bounties have to be manually funded sending ETH to the bounty contract address.

It would be great to have a Github bot listening to **bounty** issues that could allow maintainers to automatically fund the bounties.

Just reserved the @autobounty github username for it.

Example:

> @autobounty standard bounty

> @autobounty 1 ETH

And it will send the ETH to the bounty address in the issue.

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by snugghash** [comment]
I'm interested, do you welcome contributions? 

I'm thinking I'll finish this on June 11-12 or so, anyone scheduled to finish this before then?

**Comment by izqui** [comment]
I was going to try to work on this if I had time this weekend (doubt I will have much), but feel free to start it :)

My idea was to reuse most of the code [from here](https://github.com/aragon/faucet/blob/master/index.js) changing the HTTP server for a Github webhook listening for comments logic.

Wasn't planning on doing any UI, just a containerized app we add a bunch of env variables to and then it just runs the bot in the background.

I went ahead and created a repo for it at [aragon/autobounty](https://github.com/aragon/autobounty).

Let's move the conversation there!
