### ISSUE TITLE
Standardize the tense of events (nitpick)

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-core#89]
Some events are in the past tense (e.g. ``KernelReplaced``) and some are not (e.g. ``Register`` and ``Deregister``). Making them all in the same tense would be nice.

**Comment by DeveloppSoft** [comment]
If no one is working on that, I take it

**Comment by izqui** [comment]
Nice! Lets make them all past tense IMO

**Comment by DeveloppSoft** [comment]
@izqui even the one in MinimeToken? Or do you prefer to keep them as it is?

**Comment by DeveloppSoft** [comment]
I first started by making all events to the past tense, but if we look at the ezeppelin lib they seems to use present tense, maybe we should switch to present then

**Comment by DeveloppSoft** [comment]
I think past tense would seems nicer but for the sake of interoperation with third parties library, present would be nicer
